### ISSUE TITLE
Trying to get started

### ISSUE THREAD

**Issue by wingnut144** [shbisson/OverPutney#17]
I'm trying to get this installed and running, but having some issues.  My Linux is good, but not great ;)

When I run run_tracker.sh I'm getting:

will crop
Traceback (most recent call last):
  File "/home/pi/OverPutney-main/tracker.py", line 141, in <module>
    display = datasource.get_map_source()
  File "/home/pi/OverPutney-main/datasource.py", line 33, in get_map_source
    return get_driver()['map'](g_map_url)
  File "/home/pi/OverPutney-main/screenshot.py", line 66, in __init__
    self.loadmap()
  File "/home/pi/OverPutney-main/screenshot.py", line 111, in loadmap
    browser = webdriver.Chrome('/usr/bin/chromedriver', desired_capabilities=capabilities, options=options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 95.0.4638.78 with binary path /usr/bin/chromium-browser
Stacktrace:
#0 0x0055855ea568 <unknown>
#1 0x00558538263c <unknown>
#2 0x0055853a3e58 <unknown>
#3 0x0055853a08c0 <unknown>
#4 0x00558539d9a0 <unknown>
#5 0x0055853cf064 <unknown>
#6 0x0055853a6660 <unknown>
#7 0x005585617edc <unknown>
#8 0x00558562c470 <unknown>
#9 0x0055856199cc <unknown>
#10 0x00558562cc94 <unknown>
#11 0x00558560e144 <unknown>
#12 0x005585644df0 <unknown>
#13 0x005585644f58 <unknown>
#14 0x00558565d07c <unknown>
#15 0x007f839e2628 <unknown>
#16 0x007f8350f01c <unknown>

**Comment by ladewig** [comment]
Your webdriver version needs to match the version of the browser. 

```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 95.0.4638.78 with binary path /usr/bin/chromium-browser
```

This is letting you know that you're using v98 of the webdriver with v95 of the browser. Update both of those to the current release and you should be good to go.
