### ISSUE TITLE
KeyError: 'map_parameters'

### ISSUE THREAD

**Issue by PixelBoot** [shbisson/OverPutney#20]
./run_tracker.sh: line 8: bin/activate: No such file or directory

***** Restarting OverPutney  2022-06-08 12:04:29.572539427+00:00

will crop
Traceback (most recent call last):
  File "/usr/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'map_parameters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/twitter/adsb/OverLuqa/tracker.py", line 19, in <module>
    import datasource
  File "/home/pi/twitter/adsb/OverLuqa/datasource.py", line 48, in <module>
    g_map_parameters = parser.get('abovetustin', 'map_parameters')
  File "/usr/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'map_parameters' in section: 'abovetustin'

***** OverPutney exited  2022-06-08 12:04:30.299146711+00:00

**Comment by ladewig** [comment]
I've submitted pull request #21 that resolves the map_parameters issue.
